-- Seed baseline quest content (categories, quests, questions 1-2).
-- Diambil dari project awal supaya UUID quest tetap sama dengan yang dirujuk
-- migrasi 20260827153632_add_5_questions_per_quest.sql.

INSERT INTO quest_categories (id, slug, name_id, name_en, icon, sort_order, is_archived) VALUES
  ('a6faacdc-1ce7-431b-83f9-8eb5cb40ea0e', 'career', 'Karier & Tujuan', 'Career & Purpose', 'target', 1, false),
  ('efe03dd5-a071-488a-a25a-3b7c2d92e5c1', 'self_discovery', 'Penemuan Diri', 'Self-Discovery', 'sparkles', 2, false),
  ('439d73e4-4acd-4e5d-8aee-4ba8c4b60eda', 'financial', 'Keuangan', 'Financial Wellness', 'wallet', 3, false),
  ('9e851295-0054-4257-ba30-6ae9b9383aa9', 'relationship', 'Hubungan & Batasan', 'Relationship & Boundaries', 'heart', 4, false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO quests (id, category_id, title_id, title_en, description_id, description_en, tier_required, xp_reward, sort_order, is_published, is_archived) VALUES
  ('b8b933f3-948c-41e0-baf9-452247a5c9c7', 'a6faacdc-1ce7-431b-83f9-8eb5cb40ea0e', 'Cek Energi Kerjamu', 'Your Work-Life Vibe Check', 'Kenali energi kerja yang bikin kamu benar-benar hidup.', 'Discover the kind of work energy that makes you feel truly alive.', 'free', 50, 1, true, false),
  ('5ea6ab47-519a-4edf-bbc7-e02c0d94dfed', 'efe03dd5-a071-488a-a25a-3b7c2d92e5c1', 'Lounge Overthinking', 'Overthinking Lounge', 'Petakan pikiran yang berisik jadi langkah yang lebih ringan.', 'Turn noisy thoughts into lighter, smaller steps.', 'free', 50, 1, true, false),
  ('16877893-247c-492e-aea0-f259e498991f', '439d73e4-4acd-4e5d-8aee-4ba8c4b60eda', 'Isi Dompet vs Mental', 'Wallet vs Mind', 'Bikin hubungan yang lebih jujur dengan uangmu.', 'Build a more honest relationship with your money.', 'premium', 70, 1, true, false),
  ('3f116a06-dc38-4945-93db-4eac99c527f6', '9e851295-0054-4257-ba30-6ae9b9383aa9', 'Batas yang Baik', 'Healthy Boundaries', 'Belajar bilang tidak tanpa rasa bersalah.', 'Learn to say no without guilt.', 'free', 50, 2, true, false),
  ('27f2e051-4eed-403d-8759-d564a735600f', 'efe03dd5-a071-488a-a25a-3b7c2d92e5c1', 'Peta Kekuatan Diri', 'Strength Map', 'Temukan kekuatan tersembunyi yang udah ada di dalam dirimu.', 'Discover the hidden strengths already within you.', 'premium', 70, 2, true, false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO quest_questions (id, quest_id, question_type, question_id, question_en, options, sort_order) VALUES
  ('30530627-bb0c-49cb-809c-054b73368b9b', '5ea6ab47-519a-4edf-bbc7-e02c0d94dfed', 'single_choice', 'Pikiran apa yang paling sering nyangkut di kepalamu belakangan ini?', 'What thought has been lingering in your head lately?', '[{"value": "enough", "label_en": "Am I doing enough?", "label_id": "Aku udah cukup belum ya?"}, {"value": "belong", "label_en": "Do I belong here?", "label_id": "Aku cocok di sini nggak ya?"}, {"value": "future", "label_en": "What will my future look like?", "label_id": "Masa depanku bakal kayak gimana?"}, {"value": "compare", "label_en": "Why does everyone else seem ahead?", "label_id": "Kenapa orang lain kelihatan lebih maju?"}]', 1),
  ('e9a58a69-1aa5-45c0-9c38-d8a94858d611', '27f2e051-4eed-403d-8759-d564a735600f', 'single_choice', 'Aktivitas apa yang bikin kamu lupa waktu?', 'What activity makes you lose track of time?', '[{"value": "create", "label_en": "Creating something (writing, art, music).", "label_id": "Bikin sesuatu (tulis, gambar, musik)."}, {"value": "help", "label_en": "Helping others solve problems.", "label_id": "Bantu orang lain solve masalah."}, {"value": "learn", "label_en": "Learning something new and challenging.", "label_id": "Belajar hal baru yang menantang."}, {"value": "organize", "label_en": "Organizing and tidying something messy.", "label_id": "Ngatur dan rapikan sesuatu yang berantakan."}]', 1),
  ('77d92fd7-a55f-441a-bee2-6cc13b4948d5', 'b8b933f3-948c-41e0-baf9-452247a5c9c7', 'single_choice', 'Hari kerja seperti apa yang bikin kamu merasa paling jadi diri sendiri?', 'What kind of workday makes you feel most like yourself?', '[{"value": "create", "label_en": "A day with room to make things my way.", "label_id": "Hari dengan ruang buat bikin sesuatu caraku."}, {"value": "people", "label_en": "A day full of people, energy, and new ideas.", "label_id": "Hari penuh orang, energi, dan ide baru."}, {"value": "plan", "label_en": "A day with a clear plan and visible progress.", "label_id": "Hari dengan rencana jelas dan kemajuan yang kelihatan."}, {"value": "deep", "label_en": "A day that gives me time to go deep.", "label_id": "Hari yang ngasih waktu buat mendalami sesuatu."}]', 1),
  ('547ed8b2-7e46-4889-81f4-0ca5f1a3f354', '16877893-247c-492e-aea0-f259e498991f', 'single_choice', 'Saat uang masuk, hal pertama yang kamu lakukan?', 'When money comes in, what is the first thing you do?', '[{"value": "spend", "label_en": "Immediately think of what to spend it on.", "label_id": "Langsung pikir buat apa dipakai."}, {"value": "save", "label_en": "Set aside for savings first.", "label_id": "Sisihkan dulu buat tabungan."}, {"value": "plan", "label_en": "Allocate: needs, wants, savings.", "label_id": "Buat alokasi: kebutuhan, mau, tabungan."}, {"value": "worry", "label_en": "Worry it will not last the month.", "label_id": "Khawatir nggak cukup sampai akhir bulan."}]', 1),
  ('761c6fa1-8c2d-4cdf-8c14-9d7db6968e82', '3f116a06-dc38-4945-93db-4eac99c527f6', 'single_choice', 'Saat seseorang meminta sesuatu yang bikin kamu nggak nyaman, reaksi pertamamu biasanya?', 'When someone asks for something that makes you uncomfortable, what is your first reaction?', '[{"value": "yes", "label_en": "I say yes, but regret it after.", "label_id": "Aku bilang iya, tapi nyesel setelahnya."}, {"value": "maybe", "label_en": "I hesitate, but eventually agree.", "label_id": "Aku ragu, tapi akhirnya setuju."}, {"value": "no", "label_en": "I say no, but feel guilty.", "label_id": "Aku bilang tidak, tapi merasa bersalah."}, {"value": "firm", "label_en": "I say no calmly.", "label_id": "Aku bilang tidak dengan tenang."}]', 1),
  ('e6f16081-8e19-41d0-8709-e237fa9f5eed', '16877893-247c-492e-aea0-f259e498991f', 'single_choice', 'Hubunganmu dengan uang paling mirip dengan?', 'Your relationship with money is most like?', '[{"value": "friend", "label_en": "A reliable friend.", "label_id": "Teman yang bisa diandalkan."}, {"value": "stranger", "label_en": "A stranger that makes me tense.", "label_id": "Orang asing yang bikin tegang."}, {"value": "boss", "label_en": "A demanding boss.", "label_id": "Atasan yang keras kepala."}, {"value": "mystery", "label_en": "An unsolved mystery.", "label_id": "Misteri yang belum terpecahkan."}]', 2),
  ('bf29edae-ceca-4ce5-9ae3-fb1e57c92d88', 'b8b933f3-948c-41e0-baf9-452247a5c9c7', 'single_choice', 'Kamu pengen sedikit lebih banyak apa?', 'What do you want a little more of?', '[{"value": "confidence", "label_en": "Confidence", "label_id": "Percaya diri"}, {"value": "clarity", "label_en": "Clarity", "label_id": "Kejelasan"}, {"value": "courage", "label_en": "Courage", "label_id": "Keberanian"}, {"value": "calm", "label_en": "Calm", "label_id": "Ketenangan"}]', 2),
  ('4c77cd22-4adf-4c0c-b2e6-60be05e866ba', '5ea6ab47-519a-4edf-bbc7-e02c0d94dfed', 'single_choice', 'Kalau pikiran itu bisa ngomong, dia mau bilang apa?', 'If that thought could speak, what would it actually be saying?', '[{"value": "rest", "label_en": "You need rest — proof that you understand.", "label_id": "Kamu butuh istirahat, buktinya kamu ngerti."}, {"value": "slow", "label_en": "You can go slow, there is no rush.", "label_id": "Kamu boleh pelan, nggak perlu buru-buru."}, {"value": "ask", "label_en": "You can ask for help, you are not alone.", "label_id": "Kamu boleh minta bantuan, kamu nggak sendirian."}, {"value": "feel", "label_en": "You are allowed to feel, all emotions are valid.", "label_id": "Kamu boleh ngerasa, semua emosi valid."}]', 2),
  ('2364331b-09b1-4efa-b3cb-29de1100bae9', '3f116a06-dc38-4945-93db-4eac99c527f6', 'single_choice', 'Apa yang paling sering bikin kamu susah bilang tidak?', 'What most often makes it hard for you to say no?', '[{"value": "fear", "label_en": "Fear of disappointing others.", "label_id": "Takut bikin kecewa orang lain."}, {"value": "guilt", "label_en": "Feeling guilty when refusing.", "label_id": "Merasa bersalah kalau menolak."}, {"value": "conflict", "label_en": "Not wanting conflict.", "label_id": "Nggak mau ada konflik."}, {"value": "people", "label_en": "Wanting to be seen as nice.", "label_id": "Mau dilihat sebagai orang yang baik."}]', 2),
  ('c11720f6-d4bc-42bf-99d1-5dd8b0e7538d', '27f2e051-4eed-403d-8759-d564a735600f', 'single_choice', 'Komplimen apa yang paling sering kamu terima dari orang lain?', 'What compliment do you most often receive from others?', '[{"value": "listener", "label_en": "You are a great listener.", "label_id": "Kamu pendengar yang baik."}, {"value": "creative", "label_en": "You are creative and have fresh ideas.", "label_id": "Kamu kreatif dan punya ide segar."}, {"value": "calm", "label_en": "You stay calm in difficult situations.", "label_id": "Kamu selalu tenang di situasi sulit."}, {"value": "reliable", "label_en": "You are reliable.", "label_id": "Kamu bisa diandalkan."}]', 2)
ON CONFLICT (id) DO NOTHING;
